build_options:
  package_file: './build/UltimateUX.package'
  
source_files:
  xml:
    src: './src/config'
    mappings:
      - friendly_name: 'widgetlist.xml'
        name: '0333406C!00000000!DE3FB8F4E5C1A9E5.FontConfiguration.xml'

  scaleformgfx:
    src: './dst/scaleformgfx'
    actionscript:
      - src: './src/actionscript/escapemenu'
      - name: 'escapemenu.gfx'